### ISSUE TITLE
Detekcija i prepoznavanje tablica na motornim vozilima

### ISSUE THREAD

**Issue by UrosPsd** [ftn-ai-lab/ori-2021-siit#26]
## **Članovi tima:**

- Uroš Petrić, SW61-2018, grupa 4

- Ivan Luburić,  SW13-2018, grupa 1

## **Asistent:**
Veljko Maksimović

## **Problem koji se rešava:**
Sa slike na kojoj se nalazi automobil potrebno je detektovati tablicu i označiti deo slike na kojoj se ona nalazi. Posle toga je potrebno izvršiti segmentaciju karaktera sa tablice i omogućiti prepoznavanje tih karaktera. Kao izlaz se dobija slika sa označenom tablicom i karakteri koji se nalaze na njoj u vidu .txt fajla.

## **Algoritam:**
Konvolucione neuronske mreže (**YOLO**)

## **Podaci koji se koriste:**
Podaci su preuzeti sa [linka](https://github.com/openalpr/benchmarks) i predstavljaju skup slika automobila kao i rezultata u vidu karaktera sa tablice u tekstualnom formatu koji će omogućiti proveru tačnosti algoritma.

## **Metrika za merenje performansi:**
Glavni parametar za merenje performansi će biti predstavljen kroz procenat tačnosti koji se dobija poređenjem rezultata algoritma sa datim rezultatima u dataset-u.

## **Validacija rešenja:**

- Trening skup: 80%

- Validacioni skup: 20%

**Comment by VeljkoMaksimovic** [comment]
Kolege u međuvremenu je neko, pre vas, prijavio identičan projekat, gde se rešava isti problem koristeći isti pristup. Ako ste i dalje zainteresovani da radite projekat moraćete da pronađete drugi problem, ili neki drugi pristup rešavanju ovog problema.
